# -*- coding: utf-8 -*-
"""BankAuditStreamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fx8RGBQGkAw07DhJKtOOgNbnhfo1DsbI
"""
# Step 1: Install required packages
!pip install streamlit pyngrok --quiet

# Step 2: Write the app code to a file (replace with your code or use filename I created earlier)
with open("app.py", "w") as f:
    f.write('''
import streamlit as st
from streamlit.components.v1 import html

# --- Page Config ---
st.set_page_config(page_title="Your Product Landing Page", layout="wide")

# --- Custom CSS ---
custom_css = """
<style>
    .main {
        background-color: #f4f4f9;
        font-family: 'Helvetica Neue', sans-serif;
    }
    header, footer {
        background-color: #ffffff;
        padding: 1rem 2rem;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }
    .logo {
        font-size: 1.5rem;
        font-weight: bold;
        color: #3f51b5;
    }
    .nav {
        float: right;
    }
    .nav a {
        margin: 0 1rem;
        text-decoration: none;
        color: #555;
    }
    .hero {
        text-align: center;
        padding: 4rem 2rem;
        background: linear-gradient(to right, #667eea, #764ba2);
        color: white;
    }
    .features {
        padding: 3rem 2rem;
    }
    .feature-card {
        background: white;
        padding: 2rem;
        border-radius: 10px;
        box-shadow: 0 2px 8px rgba(0,0,0,0.05);
        margin-bottom: 2rem;
    }
    .cta {
        background-color: #3f51b5;
        color: white;
        padding: 3rem 2rem;
        text-align: center;
    }
</style>
"""
st.markdown(custom_css, unsafe_allow_html=True)

# --- Header ---
st.markdown("""
<header>
    <div class="logo">[Your Logo]</div>
    <div class="nav">
        <a href="#features">Features</a>
        <a href="#demo">Demo</a>
        <a href="#contact">Contact</a>
    </div>
</header>
""", unsafe_allow_html=True)

# --- Hero / Value Prop ---
st.markdown("""
<div class="hero">
    <h1>Welcome to [Your Product]</h1>
    <p>Your compelling value proposition goes here. Explain how your product solves a problem or creates value.</p>
</div>
""", unsafe_allow_html=True)

# --- Feature Showcase ---
st.markdown("<div id='features' class='features'>", unsafe_allow_html=True)
st.subheader("🌟 Key Features")
cols = st.columns(3)
for i, col in enumerate(cols):
    with col:
        st.markdown("""
        <div class="feature-card">
            <img src="https://via.placeholder.com/150" width="100%"/>
            <h3>Feature {}</h3>
            <p>Description of the feature and how it benefits the user.</p>
        </div>
        """.format(i+1), unsafe_allow_html=True)
st.markdown("</div>", unsafe_allow_html=True)

# --- Interactive Demo ---
st.markdown("<div id='demo'>", unsafe_allow_html=True)
st.subheader("🚀 Try It Out")
option = st.selectbox("Select a demo option:", ["Option A", "Option B", "Option C"])
st.write(f"You selected: {option}")
st.markdown("</div>", unsafe_allow_html=True)

# --- Call to Action ---
st.markdown("""
<div class="cta">
    <h2>Get Started with [Your Product] Today</h2>
    <p>Ready to see real impact? Contact us now or sign up for early access.</p>
</div>
""", unsafe_allow_html=True)

# --- Contact Form ---
st.markdown("<div id='contact'>", unsafe_allow_html=True)
st.subheader("📬 Contact Us")
with st.form("contact_form"):
    name = st.text_input("Name")
    email = st.text_input("Email")
    message = st.text_area("Message")
    submitted = st.form_submit_button("Send")
    if submitted:
        st.success("Thank you! We'll be in touch soon.")
st.markdown("</div>", unsafe_allow_html=True)

# --- Footer ---
st.markdown("""
<footer>
    <p>&copy; 2025 Your Company Name. All rights reserved.</p>
</footer>
""", unsafe_allow_html=True)

''')

# Step 3: Start Streamlit with ngrok tunnel
from pyngrok import ngrok
import subprocess

# Kill any previous tunnels
ngrok.kill()

# Create a tunnel to port 8501
public_url = ngrok.connect(port=8501)
print("Streamlit app is live at:", public_url)

# Run Streamlit app
process = subprocess.Popen(["streamlit", "run", "app.py"])

process.terminate()
ngrok.kill()
