# -*- coding: utf-8 -*-
"""BankAuditStreamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fx8RGBQGkAw07DhJKtOOgNbnhfo1DsbI
"""

import streamlit as st
from streamlit.components.v1 import html

# --- Page Config ---
st.set_page_config(page_title="Audit Portal", layout="wide")

# --- Custom CSS ---
custom_css = """
<style>
    .main {
        background-color: #f4f4f9;
        font-family: 'Helvetica Neue', sans-serif;
    }
    header, footer {
       background-color: #ffffff;
        padding: 1rem 2rem;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        display: flex;
        justify-content: space-between;
        align-items: center;
    }

    .logo {
        font-size: 1.5rem;
        font-weight: bold;
        color: #3f51b5;
    }
    .nav {
        float: right;
    }
    .nav a {
        margin: 0 0.75rem;
        text-decoration: none;
        color: #555;
    }
    .hero {
        text-align: center;
        padding: 4rem 2rem;
        background: linear-gradient(to right, #667eea, #764ba2);
        color: white;
    }
    .features {
        padding: 3rem 2rem;
    }
    .feature-card {
        background: white;
        padding: 2rem;
        border-radius: 10px;
        box-shadow: 0 2px 8px rgba(0,0,0,0.05);
        margin-bottom: 2rem;
    }
    .cta {
        background-color: #3f51b5;
        color: white;
        padding: 3rem 2rem;
        text-align: center;
    }
</style>
"""
st.markdown(custom_css, unsafe_allow_html=True)

# --- Header ---
st.markdown("""
<header>
    <div class="logo">The Audit Portal</div>
    <div class="nav">
        <a href="#features">Features</a>
        <a href="#demo">Demo</a>
        <a href="#contact">Contact</a>
    </div>
</header>
""", unsafe_allow_html=True)

# --- Hero / Value Prop ---
st.markdown("""
<div class="hero">
    <h1>Welcome to The Audit Portal</h1>
    <p>Auditors spend a large amount of time manually checking documents, matching records,
    and writing reports. These tasks are repetitive, error-prone, and slow, especially when
    dealing with high volumes of data. Here is your smart system that can analyze and
    explain audit data quickly and accurately. </p>
</div>
""", unsafe_allow_html=True)

# --- Feature Showcase ---
st.markdown("<div id='features' class='features'>", unsafe_allow_html=True)
st.subheader("🌟 Key Features")
cols = st.columns(3)
st.markdown(f"""
        <div class="feature-card">
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbnn0tssCtl_n6XAJ7L15NW1hgaqQghfeO0g&s" width="100%"/>
            <h3 STYLE="color:#000000">Catches More Errors & Risks (Improved Accuracy) </h3>
            <ul STYLE="color:#000000">
                <li>Instead of spending hours manually checking invoices or journal entries, the AI scans thousands of records in minutes.</li>
                <li>Auditors can now focus soley on the flagged issues, not the entire dataset</li>
                <li>Can spot patterns of fraud or errors that humans might miss—like duplicate invoices or unusual transactions at odd times.</li>
            </ul>
        </div>
        """, unsafe_allow_html=True)

st.markdown(f"""
        <div class="feature-card">
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbnn0tssCtl_n6XAJ7L15NW1hgaqQghfeO0g&s" width="100%"/>
            <h3 STYLE="color:#000000">Auto-Writes Reports (Automatic Reporting)</h3>
            <ul STYLE="color:#000000">
                <li>After analysis, the AI (via the LLM) can generate summaries, audit findings, or explanations in clear language. </li>
                <li>This saves time for the auditor and ensures consistent quality.</li>
            </ul>
        </div>
        """, unsafe_allow_html=True)

st.markdown(f"""
        <div class="feature-card">
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbnn0tssCtl_n6XAJ7L15NW1hgaqQghfeO0g&s" width="100%"/>
            <h3 STYLE="color:#000000"> Serves as a Smart Assistant (Expert Insight) </h3>
            <ul STYLE="color:#000000">
                <li>Auditors can ask the AI questions like:
                    <ul>
                        <li>“Why was this flagged?”</li>
                        <li>“Summarize all contract risks.”</li>
                    </ul>
                </li>
                <li>The model gives quick, knowledgeable answers based on the data.</li>
            </ul>
        </div>
        """, unsafe_allow_html=True)
        
st.markdown("</div>", unsafe_allow_html=True)

# --- Interactive Demo ---
st.markdown("<div id='demo'>", unsafe_allow_html=True)
st.subheader("🚀 Try It Out")
option = st.selectbox("Select a demo option:", ["Option A", "Option B", "Option C"])
st.write(f"You selected: {option}")
st.markdown("</div>", unsafe_allow_html=True)

# --- Call to Action ---
st.markdown("""
<div class="cta">
    <h2>Get Started with The Audit Portal Today</h2>
    <p>Ready to see real impact? Contact us now or sign up for early access.</p>
</div>
""", unsafe_allow_html=True)

# --- Contact Form ---
st.markdown("<div id='contact'>", unsafe_allow_html=True)
st.subheader("📬 Contact Us")
with st.form("contact_form"):
    name = st.text_input("Name")
    email = st.text_input("Email")
    message = st.text_area("Message")
    submitted = st.form_submit_button("Send")
    if submitted:
        st.success("Thank you! We'll be in touch soon.")
st.markdown("</div>", unsafe_allow_html=True)

# --- Footer ---
st.markdown("""
<footer>
    <p>&copy; 2025 Your Company Name. All rights reserved.</p>
</footer>
""", unsafe_allow_html=True)
